In [6]:
# 可以在變數後面加上 :set 告訴他明確的型別
set1:set = {1, 3, 3, 1, 9, 5, 7, 9, 11}
set1.add(12)
set1

{1, 3, 5, 7, 9, 11, 12}

In [13]:
import numpy as np

array1:np.ndarray = np.array(range(1,11))
array1 + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
display(np.arange(1.3, 3.5, 0.1))
display(np.linspace(1, 2, 20))

array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [19]:
display(np.random.random())
display(np.random.randn(10, 5, 3))
display(np.random.randint(1,10,size=(10,5)))

0.5671697760197614

array([[[ 1.04836418e-04, -2.24415264e-01,  1.00801942e+00],
        [-3.67337768e-01, -1.72776197e+00,  1.76843487e+00],
        [-1.42886655e+00,  3.33616748e-01,  6.39507984e-01],
        [ 6.80368307e-01, -1.74460476e-01,  1.16019719e+00],
        [-3.69092364e-01,  4.95965685e-01, -3.85073276e-02]],

       [[ 4.96034592e-02,  8.56884802e-01, -2.27187709e-02],
        [ 1.79247031e+00, -1.14560877e+00, -5.09418571e-01],
        [ 1.20291680e-01, -2.15376531e-01,  6.36441147e-02],
        [ 2.15918296e+00, -4.66312581e-02,  4.90793605e-01],
        [ 9.75163045e-01, -1.39367954e+00, -1.27571730e+00]],

       [[ 1.22696501e+00,  6.07573389e-01,  9.83730940e-01],
        [-4.19761911e-01, -6.93606106e-01,  6.87902679e-01],
        [ 5.61959880e-01,  1.62844860e+00, -8.77699770e-01],
        [ 5.70336809e-01, -1.41114923e+00,  6.82407443e-01],
        [ 5.71124758e-02, -1.53479824e+00, -2.48919866e-02]],

       [[-1.11504786e+00,  2.24791403e-01,  4.84720613e-02],
        [-8.802935

array([[5, 9, 6, 7, 7],
       [9, 9, 1, 8, 5],
       [2, 5, 6, 1, 4],
       [1, 2, 7, 2, 1],
       [6, 7, 7, 7, 9],
       [3, 9, 5, 2, 9],
       [6, 5, 5, 1, 5],
       [5, 7, 3, 8, 3],
       [3, 5, 3, 4, 6],
       [7, 1, 3, 2, 6]])